version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
