version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys: 
            - dependencies 
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies
      - run:
          name: Build
          command: yarn build
      - run:
          name: Prepare Deloy
          command: chmod +x ./scripts/deploy.sh
      - run:
          name: Deploy to Github Pages
          command: ./scripts/deploy.sh
